// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5K-hoF-ljy_SFA6aX1gDQ-tn6Kh25Uo',
    appId: '1:480637506909:web:5888270ffa87227ee604b4',
    messagingSenderId: '480637506909',
    projectId: 'courseappmob',
    authDomain: 'courseappmob.firebaseapp.com',
    storageBucket: 'courseappmob.appspot.com',
    measurementId: 'G-LEN12D338F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VRmy9ii6YijRVr5avfKoc_Jpd3suKps',
    appId: '1:480637506909:android:61884c1845ef0c5be604b4',
    messagingSenderId: '480637506909',
    projectId: 'courseappmob',
    storageBucket: 'courseappmob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8JNrbq-rQC79xmrilW56dMP8Htq1uaA',
    appId: '1:480637506909:ios:65d02ffa6ce2c3ebe604b4',
    messagingSenderId: '480637506909',
    projectId: 'courseappmob',
    storageBucket: 'courseappmob.appspot.com',
    iosClientId: '480637506909-ek7sqbqsdbr4d24o87n97064udrpd661.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8JNrbq-rQC79xmrilW56dMP8Htq1uaA',
    appId: '1:480637506909:ios:65d02ffa6ce2c3ebe604b4',
    messagingSenderId: '480637506909',
    projectId: 'courseappmob',
    storageBucket: 'courseappmob.appspot.com',
    iosClientId: '480637506909-ek7sqbqsdbr4d24o87n97064udrpd661.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseapp',
  );
}
